// Copies the wOS UI kit from the warOnSaaS site repo, the kit's source of truth.
// Usage: node scripts/sync-kit.mjs [path-to-site-repo]   (default ../waronsaas-site)
import fs from 'node:fs';
import path from 'node:path';

const site = process.argv[2] ?? path.resolve('..', 'waronsaas-site');
const css = fs.readFileSync(path.join(site, 'kit', 'wos.css'), 'utf8');
fs.writeFileSync('lib/ui/wos.css', css);
fs.writeFileSync('lib/ui/wos-css.mjs', `// Generated by scripts/sync-kit.mjs from warOnSaaS/site kit/wos.css. Do not edit.\nexport default ${JSON.stringify(css)};\n`);
console.log(`synced wOS kit (${css.length} bytes) from ${site}`);
