// Copies the warOnSaaS UI kit (ui-design) into lib/ui/kit.css and lib/ui/kit-css.mjs, which every page inlines.
// It reads a git ref (default main), not the working tree, so unfinished kit work never ships here.
//   node scripts/sync-kit.mjs [path-to-ui-design] [ref]   (defaults: $UI_DESIGN_DIR or ../waronsaas-ui-design, main)
// The kit's own @font-face rules are dropped: pages load their faces from Google Fonts (lib/ui/page.mjs),
// because the CSS is inlined and has no folder to load font files from.
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';

const kit = path.resolve(process.argv[2] ?? process.env.UI_DESIGN_DIR ?? path.join('..', 'waronsaas-ui-design'));
const ref = process.argv[3] ?? process.env.UI_DESIGN_REF ?? 'main';
const git = (...a) => execFileSync('git', ['-C', kit, ...a], { maxBuffer: 64 << 20 }).toString();
let rev;
try { rev = git('rev-parse', '--short', ref).trim(); }
catch { console.error(`sync-kit: no ui-design checkout with a "${ref}" branch at ${kit}. Pass its path or set UI_DESIGN_DIR.`); process.exit(1); }
const css = ['src/ui.css', 'src/tokens.css'].map((f) => git('show', `${ref}:${f}`)).join('\n')
  .replace(/@font-face\{[^}]*\}\n?/g, '');
const head = `/* warOnSaaS ui-design ${ref} at ${rev}: src/ui.css and src/tokens.css. Copied by scripts/sync-kit.mjs. Do not edit. */\n`;
fs.writeFileSync('lib/ui/kit.css', head + css);
fs.writeFileSync('lib/ui/kit-css.mjs', `// Generated by scripts/sync-kit.mjs from warOnSaaS/ui-design ${ref} at ${rev}. Do not edit.\nexport default ${JSON.stringify(css)};\n`);
console.log(`synced ui-design ${ref} ${rev} (${css.length} bytes) into lib/ui/kit.css`);
